<?php
    $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
    $storeManager = $objectManager->get('\Magento\Store\Model\StoreManagerInterface');
    $mediaUrl = $storeManager->getStore()->getBaseUrl(\Magento\Framework\UrlInterface::URL_TYPE_MEDIA);
    $_helper = $this->helper('Magento\Catalog\Helper\Output');
    $_imageHelper = $this->helper('Magento\Catalog\Helper\Image');
    $_product = $block->getProduct();
    $ctr = 0;
?>

<div class="onsale-product-container">
	<div class="productimage">
		<div style="border:1px solid #e3e3e3;">
			<?php
                $imageUrl = $_imageHelper->init($_product, 'product_base_image')
                ->constrainOnly(true)
                ->keepAspectRatio(true)
                ->keepTransparency(true)
                ->keepFrame(false)
                ->resize(900, 650)
                ->getUrl();

                $imageurl121 = $_imageHelper->init($_product, 'product_base_image')->constrainOnly(true)
                        ->keepAspectRatio(true)
                        ->keepTransparency(true)
                        ->keepFrame(false)->resize(900, 650)->getUrl();

                $tempUrl = $_imageHelper->init($_product, 'product_page_image_medium')
                ->keepAspectRatio(true)
                ->resize(1024, 768)->getUrl();

                $imageLargeUrl = str_replace('\\','/',$tempUrl);
                if (!file_exists($imageUrl)) {		
                  $imageUrl;
                } else {
                   $imageUrl = $this->getViewFileUrl('images/catalog/product/placeholder/placeholder.png');
                }

            ?>
			<?php if ($_product->getUnilabRx() == 1) :  ?>
			<div id="rx-big"><img id="rx-big-img" src="<?php echo $this->getViewFileUrl('images/rx_red_big.png'); ?>" /></div>
			<?php endif; ?>
			<img
                id="zoom_03"
                class="prod-image"
                style="width: 100%;"
                src="<?php echo $imageUrl; ?>"
                data-zoom-image="<?php echo $imageLargeUrl;?>"
                border="1"
                datatest="<?php echo $imageLargeUrl;?>"/>
		</div>
	</div>

    <!-- Thumbnails -->
    <div id="galleria" style="height: auto; margin-top: 0.5rem;">
        <?php
            foreach ($block->getGalleryImages() as $_image):
                $imageurl =  $_imageHelper->init($_product, 'product_base_image')
                ->setImageFile($_image->getFile())
                ->constrainOnly(true)
                ->keepAspectRatio(true)
                ->keepTransparency(true)
                ->keepFrame(false)->resize(900, 650)->getUrl();

                //if (@getimagesize($imageurl)) {
                    $imageurl;
               // } else {
                  //  $imageurl = $this->getViewFileUrl('images/catalog/product/placeholder/placeholder.png');
               // }
        ?>

            <a href="#" data-image="<?php echo $imageurl; ?>" data-zoom-image="<?php echo str_replace('\\','/',$_imageHelper->init($_product, 'product_base_image')->setImageFile($_image->getFile())->constrainOnly(true)
                ->keepAspectRatio(true)
                ->keepTransparency(true)
                ->keepFrame(false)->resize(1024, 768)->getUrl()); ?>">
                <img id="<?php echo "img_" . $ctr; ?>" style="border: 1px solid #eee; width: 120px; height:120px" src="<?php echo $imageurl; ?>"  />
            </a>
        <?php
                $ctr++;
            endforeach; ?>
    </div>
</div>

<script type="text/javascript">
//<![CDATA[
    require([
        'jquery',
        'elavateZoom'
    ], function($){
        console.log($("#zoom_03").elevateZoom({
            constrainSize:700,
            zoomType: "lens",
            containLensZoom: true,
            gallery:'galleria',
            cursor: 'pointer',
            galleryActiveClass: "active",
        }));
    });
//]]>
</script>
