
<style>
	.heading
	{
		padding:4px 10px 0px 10px;
		background-color: <?= $skins['skin_header_background']; ?>;
		border-radius:8px 8px 0px 0px;
		height: 33px;
		
	}
	.cls_number
	{
		display:inline-block;
		font-size:14px;
		border:solid 1px #fff;
		padding:2px 5px 2px 5px;
		border-radius:5px;
		background-color: <?= $skins['skin_header_pagination_background']; ?>;
		color: <?= $skins['skin_header_pagination_text']; ?>;
		font-weight:bold;
	}
	.cls_header
	{
		display:inline-block;
		font-size:14px !important;
		padding:2px 5px 2px 5px;
		border-radius:5px;
		font-weight:bold;
		margin-top: 0;
		color: <?= $skins['skin_header_text']; ?>
	}	
	.shipping_wrapper, .shipping_method_wraper,.payment_method_wraper,.items_wrapper
	{
		position: relative;
		border: solid 1px <?= $skins['skin_body_border']?>;
		background-color: #FFFFFF;
		border-radius: 10px 10px 0px 0px;
		display: inline-block;
		width: 100%;
		
	}
	.total_wrapper
	{
		position:relative;
		background-color: <?= $skins['skin_body_background'];?>;
		display:inline-block;
		width: 100%;
		
	}
	.cls_body
	{
		padding:10px;
		color: #333 !important;
		/* font-family: 'calibriregular'; */
		font-size: 14px !important;
		line-height: 1.42857143 !important;
	}
	.name-firstname, .name-lastname,.field-telephone,.field-mobile, .gender, .fax
	{
		display:inline-block;
		width:49%;
	}
	.customer-name, .postcode-region, .telephone-mobile, .customer-dob-gender, .faxgender
	{
		width: 365px;
		max-width: 100%;
	}
	
	.field-postcode
	{
		display:inline-block;
		width:24%;
	}	
	.field-region
	{
		display:inline-block;
		width:74%;
	}
	.cls_address
	{
		display:inline-block;
		width:45%;
	}
	.container_wapper
	{
		position:relative;
		padding-left:15px;
	}
	#shopping-cart-table
	{
		width: 100% !important;
	}

	#checkout_totals {
		text-align: right;
	}
	.form-list
	{
		width:100% !important;
	}
	.form-list li {
	  margin: 5px 0px 5px 0px !important;
	}	
	.input-box select 
	{
		padding: 4px 4px 7px;
		width: 99%;
	}
	.form-list li.wide .input-box input.input-text 
	{
	  width: 94%;
	}	
	/* .heading{
		background-color: initial !important;
		background: #8dcb46;
		background: url(data:image/svg+xml;base64,PD94bWwgdmVyc2lvbj0iMS4wIiA/Pgo8c3ZnIHhtbG5zPSJod…EiIGhlaWdodD0iMSIgZmlsbD0idXJsKCNncmFkLXVjZ2ctZ2VuZXJhdGVkKSIgLz4KPC9zdmc+);
		background: -moz-linear-gradient(top, #8dcb46 48%, #5d793c 96%);
		background-color: rgba(0, 0, 0, 0);
		background: -webkit-gradient(linear, left top, left bottom, color-stop(48%,#8dcb46), color-stop(96%,#5d793c));
		background: -webkit-linear-gradient(top, #8dcb46 48%,#5d793c 96%);
		background: -o-linear-gradient(top, #8dcb46 48%,#5d793c 96%);
		background: -ms-linear-gradient(top, #8dcb46 48%,#5d793c 96%);
		background: linear-gradient(to bottom, #7fb640 48%,#698f3d 96%);
		filter: progid:DXImageTransform.Microsoft.gradient( startColorstr='#8dcb46', endColorstr='#5d793c',GradientType=0 );
		height: 29px;
	} */
	h1, h2, h3, h4, h5, h6 {
		padding: 0;
		margin: 0 0 18px;
		clear: both;
	}
	.data-table thead, .data-table thead tr {

		background: #e9e9e9;
		border-bottom: 2px solid #6A6E6E !important;
		border-top: 2px solid #6A6E6E !important;

	}
	.loadingbar, .updatingbar{
		position: fixed;
		top: 25%;
		left: 35%;
		background-color: #fff;
		padding: 10px;
		width: 30%;
		display:none;
	}
	.button {
		background: #4b599f !important;
		padding: 8px 10px !important;
		box-shadow: 1px 5px 12px 1px rgba(182, 173, 173, 0.99);
	}
	.button {
		background: -webkit-gradient( linear, left top, left bottom, color-stop(0.05, #A40328), color-stop(1, #A40328) );
		background: -moz-linear-gradient( center top, #A40328 5%, #A40328 100% );
		filter: progid:DXImageTransform.Microsoft.gradient(startColorstr='#F7F7F7', endColorstr='#dfdfdf');
		background-color: #208881;
		-moz-border-radius: 3px;
		-webkit-border-radius: 3px;
		border-radius: 3px;
		border: none;
		display: inline-block;
		color: #fff;
		font-weight: bold;
		font-size: 12px;
		padding: 3px 10px 5px;
		text-decoration: none;
		text-transform: uppercase;
		*margin-right: 10px;
	}
	.a-right {
		text-align: right;
	}
	.shippingaddress {
		width: 101%;
	}
	#billing_street1{
		width: 99%;
	}
	em {
		color: red;
	}
</style>