<div id="askPrescription" style="width:300px;margin-top:20px;margin-bottom:10px;"> 
	<h3 style="text-align: center">Do you have a prescription?</h3>
	<p style="text-align: center;margin: 0 auto;width: 224px;">
		<input type="button" class="btn btn-primary btn-block btn-prescription" value="YES" id="has_prescription"/>
		<input type="button" class="btn btn-primary btn-block btn-prescription" value="NO" id="no_prescription"/>
	</p>
</div>
