<div id="cancelPrescription" style="width:300px;height:130px;margin-top:20px;margin-bottom:10px;"> 
	<h3><?php echo __("You have indicated that you do not have a prescription.");?></h3>
	<p><?php echo __("For your safety, we can only process orders with a prescription.");?></p>
	
	<p style="text-align: center;margin: 0 auto;width: 224px;">
		<input type="button" name="close" class="button" id="btnCancelPrescription" value="<?php echo __("Ok");?>"/>
	</p>
</div> 
<div style="display:none;" id="form_wrapper_cancelled"></div>