<div id="cancelPrescriptionTransaction" style="width:390px;height:145px;margin-top:20px;margin-bottom:10px;overflow:hidden;"> 
	<h3><?php echo __("Are you sure you want to cancel this transaction?");?></h3> 
	<p style="text-align: center;margin: 0 auto;width: 224px;">	
		<input type="button" name="close" class="button" id="btnCancelPrescriptionTransaction" value="<?php echo __("Yes");?>"/>
		<input type="button" name="close" class="button" id="btnCancelPrescriptionCancelTransaction" value="<?php echo __("No");?>"/>
	</p>
</div>   