<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var \Magento\Wishlist\Block\Customer\Wishlist\Item\Column\Image $block */

/** @var \Magento\Wishlist\Model\Item $item */
$item = $block->getItem();
$product = $item->getProduct();
?>
<td data-th="Image" >
    <div style="position:relative;">
        <?php if($product->getUnilabRx()):?>
        	<div class="productrxcart"></div>
        <?php endif;?>
        <a class="product-item-photo" tabindex="-1" href="<?= $block->escapeUrl($block->getProductUrl($item)) ?>" title="<?= $block->escapeHtmlAttr($product->getName()) ?>">
            <?= $block->getImage($product, 'wishlist_thumbnail')->toHtml() ?>
        </a>
    </div>
</td>
