<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var \Magento\Wishlist\Block\Customer\Wishlist\Item\Column\Info $block */

/** @var \Magento\Wishlist\Model\Item $item */
$item = $block->getItem();
$product = $item->getProduct();
?>
<td data-th="Name">
    <strong class="product-item-name">
        <h3 style="margin-top:0!important;">
            <a href="<?= $block->escapeUrl($block->getProductUrl($item)) ?>" title="<?= $block->escapeHtmlAttr($product->getName()) ?>" class="product-item-link">
                <?= $block->escapeHtml($product->getName()) ?>
            </a>
        </h3>
        <div class="description std">
            <div class="inner">
                <?php echo $block->escapeHtml($block->stripTags($product->getShortDescription()));?>
            </div>
        </div>
    </strong>
</td>
