<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php $_order = $block->getOrder() ?>
<?php if ($_order): ?>
    <?php $_items = $_order->getAllItems(); ?>
    <table class="email-items" cellspacing="0" cellpadding="0" border="0" width="650" style="margin:0 auto;border:1px solid #208881;">
        <thead>
            <tr>
                <th align="center" bgcolor="#303030" style="font-size:13px; padding:3px 9px; background:#303030; color:#FFFFFF;">SKU</th>
                <th align="center" bgcolor="#303030" style="font-size:13px; padding:3px 9px; background:#303030; color:#FFFFFF;">Items Description</th>
                <th align="center" bgcolor="#303030" style="font-size:13px; padding:3px 9px; background:#303030; color:#FFFFFF;">Qty</th>
                <th align="center" bgcolor="#303030" style="font-size:13px; padding:3px 9px; background:#303030; color:#FFFFFF;">Price</th>
                <th align="center" bgcolor="#303030" style="font-size:13px; padding:3px 9px; background:#303030; color:#FFFFFF;">Total</th>
            </tr>
        </thead>
        <?php foreach ($_items as $_item): ?>
            <?php
                if ($_item->getParentItem()) {
                    continue;
                }
            ?>
            <tbody>
                <?= $block->getItemHtml($_item) ?>
            </tbody>
        <?php endforeach; ?>
    </table>
    <table cellspacing="0" cellpadding="0" border="0" width="650" style="border:0; margin:0 auto;">
        <tbody>
            <?php echo $this->getChildHtml('order_totals') ?>
        </tbody>
    </table>
    <br/>
    <?php if ($this->helper('Magento\GiftMessage\Helper\Message')->isMessagesAllowed('order', $_order, $_order->getStore()) && $_order->getGiftMessageId()): ?>
        <?php $_giftMessage = $this->helper('Magento\GiftMessage\Helper\Message')->getGiftMessage($_order->getGiftMessageId()); ?>
        <?php if ($_giftMessage): ?>
            <br />
            <table class="message-gift">
                <tr>
                    <td>
                        <h3><?= /* @escapeNotVerified */  __('Gift Message for this Order') ?></h3>
                        <strong><?= /* @escapeNotVerified */  __('From:') ?></strong> <?= $block->escapeHtml($_giftMessage->getSender()) ?>
                        <br /><strong><?= /* @escapeNotVerified */  __('To:') ?></strong> <?= $block->escapeHtml($_giftMessage->getRecipient()) ?>
                        <br /><strong><?= /* @escapeNotVerified */  __('Message:') ?></strong>
                        <br /><?= $block->escapeHtml($_giftMessage->getMessage()) ?>
                    </td>
                </tr>
            </table>
        <?php endif; ?>
    <?php endif; ?>
<?php endif; ?>
