<div class="col-main">
<table>
<tbody>
<tr><th style="width: 200px;">
<p><img src="{{media url="wysiwyg/etc/sidebar_addtocart.JPG"}}" alt="" /></p>
<div></div>
<p>{{widget type="Magento\Catalog\Block\Product\Widget\NewWidget" display_type="all_products" show_pager="0" products_count="3" template="product/widget/new/column/new_default_list.phtml"}}</p>
</th><th>
<div class="page-title">
<h4>Delivery Policy</h4>
</div>
<div class="std">
<div class="psslai-content-box">
<p><strong>ActiveOneRX</strong> has Xend Business Solutions to handle your deliveries. Expect your purchases to be delivered to your <br /> specified address within 5 working days; however, we cannot guarantee all orders to be delivered on time due to the <br /> possibility of unforeseeable circumstances. Upon ordering, an e-mail confirmation will be sent to you along with a tracking <br /> reference number for your use in the activeonerx.com.ph site.</p>
<p> In the event though that delay in delivery is encountered, please note that ActiveOneRX shall not be liable for any losses,<br /> liabilities, costs, damages, charges, or expenses arising out of the late delivery.</p>
<p> In case that the delivery could not be received, we will leave an info card at the delivery location with detailed instructions on<br /> how you can request your delivery from Xend's dispatch unit.</p>
<p> As safeguard, please inspect the product for any defects or damage before signing to confirm the delivery and remember <br />to keep the receipt of the delivered product. In the rare instance that your item has defect, or your order is incomplete,<br /> please get in touch with our Customer Service team at <strong>(02) 6572288</strong> or e-mail us at <strong><a href="mailto:activeonerx@activeonehealth.com"> <span lang="EN-US">activeonerx@activeonehealth.com</span></a></strong>.</p>
</div>
</div>
</th></tr>
</tbody>
</table>
</div>
