<div class="col-main">
<table>
<tbody>
<tr><th style="width: 200px;">
<p><img src="{{media url="wysiwyg/etc/sidebar_addtocart.JPG"}}" alt="" /></p>
<div></div>
<p>{{widget type="Magento\Catalog\Block\Product\Widget\NewWidget" display_type="all_products" show_pager="0" products_count="3" template="product/widget/new/column/new_default_list.phtml"}}</p>
</th><th>
<div class="page-title">
<h4>FREQUENTLY ASKED QUESTIONS</h4>
</div>
<div class="std">
<div id="term-wrapper">
<div id="description" class="wrapper">
<p><strong>How can I pay online?</strong></p>
<p>You can pay using your MasterCard or Visa credit card, BancNet accredited ATM Card, or RCBC AccessOne Account.<br /> Payment fulfillment is through secured gateways – BPI-Secure Pay and Dragon Pay.</p>
<p><strong>Is the site safe for payment by credit cards?</strong></p>
<p>Yes! ActiveOneRX uses Verisign’s Security Certificate which enables end-to-end encryption and allows you to verify <br /> the authenticity of our site.</p>
<p><strong>How long will it take to get my purchases delivered?</strong></p>
<p>Your purchases will be delivered to your specified address within 5 working days from the time the order was<br /> placed. Once the goods are dispatched from the warehouse, you will receive an email notification that your package<br /> is on transit. In the email, a Tracking ID is provided which you can use to track your order. In the event that you <br /> don’t receive your order after 3 days, you may call our customer service hotline at <strong>(02) 6572288</strong>.</p>
<p><strong>I have difficulty in logging into the system? What can I do?</strong></p>
<p>Make sure you have entered the correct email address and password. If you forgot your password, click on <br /> the “Forgot Password” icon and follow the instructions. For other concerns, please contact our customer service <br /> hotline no <strong>(02) 6572288.</strong></p>
</div>
</div>
</div>
</th></tr>
</tbody>
</table>
</div>
