<div class="box-container">
    <div class="page-title">
        <h4>Return Policy</h4>
    </div>
    <div class="std">
        <div class="psslai-content-box">
            <p>In protecting the integrity of our products, and in consideration that they must follow strict storage conditions and various<br /> regulations, the following will be observed:</p>
            <p>1. Return of items will be accepted on a case to case basis determined by our Quality Assurance Team.</p>
            <p>2. Items in good condition may be returned within three (3) working days upon receipt of the items.</p>
            <p>3. ActiveOneRX does not accept returns of the following items: a. Loose items (capsule, tablets, etc.), b. Injectables - vials, <br /> ampules, syringes, c. Biologicals and other refrigerated items - vaccines, insulins, etc.</p>
            <p>4. Customer must e-mail a copy of Official Receipt / Delivery Receipt to <strong><a href="mailto:customersupport@activeone.com"><span lang="EN-US">customersupport@activeone.com</span></a></strong>. </p>
            <p>5. Returned items must be in the original sealed container, not damaged or adulterated.</p>
            <p>6. Refunds, net of any service fee, will be processed after receipt of the returned items in good condition.</p>
        </div>
    </div>
</div>
