<div class="box-container">
    <div class="page-title">
    <h3>Terms and Condition</h3>
    </div>
    <div class="std">
    <div class="std">
    <div>
    <p>Before accessing this site, please take time to read and review the terms and conditions carefully. By accessing this site, you</p>
    <p>represent and warrant to us that you have read and understood, and agree to, the terms and conditions set forth below.</p>
    <p>If you do not agree, we advise that you refrain from accessing this site.</p>
    </div>
    </div>
    </div>
    <ul style="margin-left: 35px; list-style:circle;">
    <li>Prices are subject to change without prior notice.</li>
    <li>This site is not directed at children, and the services being offered are for individuals who are at least 18 years of age. <br /> Any person under 18 years old who wishes to avail of the services must provide us in advance the relevant consent from <br /> his/her parent. Should anyone whom we know to be under 18 years old access the site and manifest his/her intention to<br /> avail of the services, we will use the information so disclosed by such minor only to respond and inform him/her that we<br /> must have his/her parental consent before he/she can avail of the services being offered in this site.</li>
    <li>The contents of this site are provided for information purposes only. It shall in no way be construed as a substitute for a <br /> professional medical advice and should not be relied upon in that regard. For diagnosis, treatment and prescription,<br /> consult your physician and other healthcare providers. You undertake to carefully read all product packaging and labels <br /> prior to use. Consult your physician and other healthcare providers before taking any goods being offered in this site.</li>
    <li>For prescription medicine, we will not dispense the same without prescription from your physician.</li>
    <li>The contents of this are provided “as is”. WORK-PLACE PHARMACY SERVICES, INC. (WPSI), its affiliates, partners, <br /> agents and/or suppliers make no warranties, expressed or implied, and hereby disclaim and negate all other warranties, <br /> including without limitation, implied warranties or conditions of merchantability, fitness for a particular purpose, or <br /> non-infringement of intellectual property or other violation of rights.</li>
    <li>Further, they do not warrant or make any representations concerning the accuracy, likely or desired results, or reliability<br /> of the use of the goods. If at all, WPSI, its affiliates, partners, agents and/or suppliers only liability is to replace the goods<br /> found to be defective or reimburse/credit you the equal amount of the purchase price of the goods. In no event shall WPSI,<br /> its affiliates, partners, agents and/or suppliers be liable for any special, consequential, indirect, exemplary or incidental<br /> damages whatsoever resulting from the use of the goods or availing of the services being offered, whether such claim<br /> is based on contract, tort (including negligence), product liability or otherwise, even if advised of the possibility or<br /> likelihood of such damages.</li>
    <li>For returns, please see FAQ for complete details. We reserve our right to revise and amend our return policy from time<br /> to time. You undertake to review the return policy each time you avail of the services being offered in this site.</li>
    <li>Customer warrants that the purchase of the products will not violate any laws. As such, Customer hereby holds WPSI free<br /> and harmless from any and all loss or damage arising from or in connection with the breach of this warranty by the Customer.</li>
    <li>Customer shall be responsible in engaging the local courier to whom the products will be delivered by WPSI. WPSI obligation<br /> ends upon delivery of the products to customer’s local courier and shall not be responsible to shipment to be made thereafter, <br /> including to foreign destination.</li>
    <li>The terms and conditions shall be governed by the laws of the Republic of the Philippines, without regard to its conflicts of <br /> laws principles. Any legal action or proceeding related to this shall be brought before the appropriate courts in Mandaluyong <br /> City, Philippines, to the exclusion of all other courts.</li>
    </ul>
</div>
