<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php
/** @var \Magento\Wishlist\Block\Customer\Wishlist\Items $block */
$columns = $block->getColumns();
?>

<table class="my-favorites-table">
    <thead style="border-top:none!important;border-bottom:none!important;">
        <tr>
            <th><?=__('')?></th>
            <th><?=__('Product')?></th>
            <th><?=__('Price')?></th>
            <th><?=__('Qty')?></th>
        </tr>
    </thead>
    <tbody>
        <?php $iterator = 1; ?>
        <?php if (count($block->getItems())): ?>
            <?php foreach ($block->getItems() as $item): ?>
            <?= /* @noEscape */ ($iterator++ == 1) ? '<tr data-row="product-item" class="product-item" id="item_' . $block->escapeHtmlAttr($item->getId()) . '">' : '</tr><tr class="product-item" id="item_' . $block->escapeHtmlAttr($item->getId()) . '">' ?>
                <?php foreach ($columns as $column): ?>
                    <?php $column->setItem($item); echo $column->toHtml($item);?>
                <?php endforeach; ?>
            <?= ($iterator == count($block->getItems())+1) ? '</tr>' : '' ?>
            <?php endforeach; ?>
        <?php else: ?>
            <tr class="message info empty">
                <td colspan="3"><span><?= $block->escapeHtml(__('You have no items in your favorites.')) ?></span></td>
            </tr>
        <?php endif; ?>
    </tbody>
</table>
