
<?php

?>
<div class="checkout-success">
    <p><b><?php echo __('Please check your email for your reference no. and other instruction(s).')?></b></p>
   
	<p><b><?php echo __('You may click on <a href="'.$this->getUrl('customer/account').'">'.  __('My Account').'</a> to view details of your order.</span>')?></b></p>

    <div class="actions-toolbar">
        <div class="primary">
            <a class="action primary continue" href="<?= /* @escapeNotVerified */ $block->getContinueUrl() ?>"><span><?= /* @escapeNotVerified */ __('Continue Shopping') ?></span></a>
        </div>
    </div>
</div>
<style type="text/css">            
    .block-layered-nav{
        display: none;
    }
    .block-title{
    	display: none;
    }
</style>