<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var \Magento\Customer\Block\Newsletter $block */
?>
<div class="newsletter-box">
    <?= $block->getChildHtml('form_before') ?>
        <form class="form form-newsletter-manage" action="<?= $block->escapeUrl($block->getAction()) ?>" method="post" id="form-validate">
            <fieldset class="fieldset">
                <?= $block->getBlockHtml('formkey') ?>
                <legend class="legend subscription-legend"><span><?= $block->escapeHtml(__('Subscription option')) ?></span></legend><br>
                <div class="field choice">
                    <input type="checkbox" name="is_subscribed" id="subscription" value="1" title="<?= $block->escapeHtmlAttr(__('General Subscription')) ?>"<?php if ($block->getIsSubscribed()): ?> checked="checked"<?php endif; ?> class="checkbox">
                    <label for="subscription" class="label"><span><?= $block->escapeHtml(__('General Subscription')) ?></span></label>
                </div>
                <?php /* Extensions placeholder */ ?>
                <?= $block->getChildHtml('customer.form.newsletter.extra') ?>
            </fieldset>
            <div class="actions-toolbar subscription-toolbar">
                <div class="primary"><button type="submit" title="<?= $block->escapeHtmlAttr(__('Save')) ?>" class="action save primary"><span><?= $block->escapeHtml(__('Save')) ?></span></button></div>
            </div>
            <div class="back-button">
                <div class="secondary">
                    <small>« </small>
                    <a class="action back" href="<?= $block->escapeUrl($block->getBackUrl()) ?>"><span><?= $block->escapeHtml(__('Back')) ?></span></a>
                </div>
            </div>
        </form>
    <?php /* Extensions placeholder */ ?>
    <?= $block->getChildHtml('customer.form.newsletter.extra2') ?>
</div>
