<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var \Magento\Customer\Block\Widget\civil_status $block */

?>
<div class="field civil_status<?php if ($block->isRequired()) echo ' required' ?>">
    <label class="label" for="<?= $block->escapeHtmlAttr($block->getFieldId('civil_status')) ?>"><span><?= $block->escapeHtml(__('Civil Status')) ?></span></label>
    <div class="input-box">
        <select id="<?= $block->escapeHtmlAttr($block->getFieldId('civil_status')) ?>" name="<?= $block->escapeHtmlAttr($block->getFieldName('civil_status')) ?>" title="<?= $block->escapeHtmlAttr(__('Civil Status')) ?>"<?php if ($block->isRequired()):?> class="validate-select" data-validate="{required:true}"<?php endif; ?>>
            <?php $options = $block->getCivilStatusOptions(); ?>
            <?php $value = $block->getCivilStatus();?>
            <?php foreach ($options as $option):
                ?>
                <option value="<?= $block->escapeHtmlAttr($option['value']) ?>"<?php if ($option['value'] == $value) echo ' selected="selected"' ?>><?= $block->escapeHtml(__($option['label'])) ?></option>
            <?php endforeach;?>
        </select>
    </div>
</div>
