<?php
$objectManager =  \Magento\Framework\App\ObjectManager::getInstance();
$storeManager = $objectManager->get('\Magento\Store\Model\StoreManagerInterface');
$baseUrl = $storeManager->getStore()->getBaseUrl();
$mediaUrl = $storeManager->getStore()->getBaseUrl(\Magento\Framework\UrlInterface::URL_TYPE_MEDIA );
?>

<p style="text-align: center; margin-top: 1rem;"><img id="add-to-cart" style="cursor: pointer; height: 127px; width: 180px;" 
src="<?=$mediaUrl.'wysiwyg/freeshipping.jpg"'?>" alt="" /></p>
<script type="text/javascript" xml="space">// <![CDATA[
// 
    require([
        'jquery',
        'fancybox'
    ], function($, fancybox){
        $('#add-to-cart').click(function (){ 
        $.fancybox.showLoading();
                $.post( '<?=$baseUrl."addmultipleproducts/addproducts/addmultiple"?>', 
                    {  
                    }, 
                    function (response){ 
                            if(response == '<?=$baseUrl."checkout/cart/"?>'){
                                window.location.replace(response);
                            } else{
                                $.fancybox.hideLoading();
                                var temp =
                                '<div id="add-failed"'+ 'style="width:300px;height:80px;margin-top:20px;margin-bottom:10px;">'+ 
                                    '<h3 style="text-align: center">'+response.replace(/\\/g, '')+'</h3>'+		
                                '</div>';
                                        $.fancybox({content: temp, 
                                    closeBtn: true, 
                                    closeClick: true, 
                                    helpers: { overlay : {closeClick : true, 
                                                        locked:      false}} 
                                    }); 
                            }
                }); 
            });
    })
// 
// ]]></script>