<?php
/**
 * Top menu for store
 *
 * @var $block \Magento\Theme\Block\Html\Topmenu
 */
?>
<?php $columnsLimit = $block->getColumnsLimit() ?: 0; ?>
<?php $_menu = $block->getHtml('level-top', 'submenu', $columnsLimit) ?>
<?php
    $objectManager =  \Magento\Framework\App\ObjectManager::getInstance();
    $storeManager = $objectManager->get('\Magento\Store\Model\StoreManagerInterface');
    $categoryHelper = $objectManager->get('\Magento\Catalog\Helper\Category');
    $categoryRepository = $objectManager->get('\Magento\Catalog\Model\CategoryRepository');
    $categoryModel = $objectManager->get('\Magento\Catalog\Model\Category');
    $storeId = $storeManager->getStore()->getId();
    $rootCategoryId = $storeManager->getStore($storeId)->getRootCategoryId();
    $rootCategory = $categoryRepository->get($rootCategoryId);
    $subCategories = $rootCategory->getChildrenCategories();
    $temp = array(
        'store_id' => $storeId,
        'category_id' => $rootCategoryId,
        'children' => $categoryRepository->get($rootCategoryId)
    );
?>
<div class="main-nav">
	<a class="toggle-nav" href="#">☰</a>
	    <nav class="res-menu">
 			<ul class="category-menu">
                <?php foreach($subCategories as $category): ?>
                    <li id="<?=$category->getId()?>">
                        <a href="<?=$category->getUrl()?>?cat=<?=$category->getId()?>"> <?=$category->getName();?></a>
                    </li>
                <?php endforeach;?>
            </ul>
    	</nav>
    </div>
</div>

<input type="hidden" name="category_id_param" value="<?=isset($_GET['cat']) ? $_GET['cat'] :NULL;?>">
 <!--End div container1 from custom_logo_header.phtml-->

<script type="text/javascript">
    require([
        'jquery'
    ], function($){
        var catID = $('input[name=category_id_param]').val();
        $('#'+catID).addClass('category-active');
        // console.log(catID)

        $(".toggle-nav").on("click", function(e) {
            $("ul.category-menu").toggle();
        })
    })
</script>
