
<?php $storeName = $block->getThemeName() ? $block->getThemeName() : $block->getLogoAlt();
?>
<!-- <span data-action="toggle-nav" class="action nav-toggle"><span><?= /* @escapeNotVerified */ __('Toggle Nav') ?></span></span> -->
<div class="container1">
<?php if ($block->isHomePage()):?>
    <div class="image-logo">
<?php else: ?>
    <a class="logo" href="<?= $block->getUrl('') ?>" title="<?= /* @escapeNotVerified */ $storeName ?>">
<?php endif ?>
        <img src="<?= /* @escapeNotVerified */ $block->getLogoSrc() ?>"
             alt="<?= /* @escapeNotVerified */ $block->getLogoAlt() ?>"
             <?= $block->getLogoWidth() ? 'width="' . $block->getLogoWidth() . '"' : '' ?>
             <?= $block->getLogoHeight() ? 'height="' . $block->getLogoHeight() . '"' : '' ?>
        />
<?php if ($block->isHomePage()):?>
    </<div>
<?php else:?>
    </a>
<?php endif?>
</div>