<div class="footer-highlight">
	<div class="footer-wrapper">
		<div class="row flex">
			<div class="footer-featured col-md-3 col-sm-3">
				<h3>Customer Service</h3>
					<ul>
						<li><a href="contact-us">Contact Us</a></li>
						<li><a href="faqs">FAQs</a></li>
						<li><a href="delivery-policy">Delivery Policy</a></li>
						<li><a href="return-policy">Return Policy</a></li>
					</ul>
			</div>
	
			<div class="footer-featured col-md-3 col-sm-3">
				<h3>About Us</h3>
				<ul>
					<li><a href="aboutus">ActiveOneRx</a></li>
					<li><a href="terms-and-condition">Terms and Condition</a></li>
					<li><a href="privacy-policy">Privacy Policy</a></li>
				</ul>
			</div>
	
			<div class="footer-featured col-md-3 col-sm-3 fl-right">
				<h3>Secured Payment Methods</h3>
				<ul>
					<li><img src="<?php echo $this->getViewFileUrl('images/icon-securepay.png'); ?>"></li>
					<li><img style="width:141px;height:41px" src="<?php echo $this->getViewFileUrl('images/logo_dragonpay.png'); ?>"></li>
				</ul>
			</div>
	
			<div class="footer-featured col-md-3 col-sm-3">
				<h3>Shipping Method</h3>
				<ul>
					<li>
						<a href="http://new.xend.com.ph/" target="_blank">
							<img src="<?php echo $this->getViewFileUrl('images/icon-xend.png'); ?>"/>
						</a>
					</li>
				</ul>
			</div>
		</div>

		<!-- <div class="row">
			
		</div> -->
	</div>
</div>
<?php echo $this->getChildHtml("copyright") ?>