<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/**
 * @var $block \Magento\Theme\Block\Html\Title
 */

/**
 * Custom
 */
    $urlInterface = \Magento\Framework\App\ObjectManager::getInstance()->get('Magento\Framework\UrlInterface');
    $strfilter = $this->getRequest()->getParam('strfilter');
    $tid = $this->getRequest()->getParam('tid');
    $fid = $this->getRequest()->getParam('fid');
    $bid = $this->getRequest()->getParam('bid');
    $sid = $this->getRequest()->getParam('sid');

    $isCartPage = (strpos($urlInterface->getCurrentUrl(),'/checkout/cart/index/')) || (strpos($urlInterface->getCurrentUrl(),'/checkout/cart/')) !== FALSE ? "shopping-cart-page-title" : "";
 /**
  * ENd Customer
  */
    $cssClass = $block->getCssClass() ? ' ' . $block->getCssClass() : '';
    $title = '';
    if(!isset($_GET['strfilter']) || !isset($_GET['tid']) || !isset($_GET['fid']) || !isset($_GET['bid']) || !isset($_GET['sid'])):
        if (trim($block->getPageHeading())) {
            $title = '<span class="base" data-ui-id="page-title-wrapper" ' .  $block->getAddBaseAttribute() . '>'
                . $block->escapeHtml($block->getPageHeading()) . '</span>';
        }
?>
        <?php if ($title): ?>
        <div class="page-title-wrapper<?= /* @escapeNotVerified */ $cssClass ?>">
            <h1 class="page-title <?=$isCartPage;?>"
                <?php if ($block->getId()): ?> id="<?= /* @escapeNotVerified */ $block->getId() ?>" <?php endif; ?>
                <?php if ($block->getAddBaseAttributeAria()): ?>
                    aria-labelledby="<?= /* @escapeNotVerified */ $block->getAddBaseAttributeAria() ?>"
                <?php endif; ?>>
                <?= /* @escapeNotVerified */ $title ?>
            </h1>
            <?= $block->getChildHtml() ?>
        </div>
        <?php endif; ?>
    <?php endif;?>
