<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var \Magento\Framework\View\Element\Template $block */
?>
<p><?= $block->escapeHtml(__('You have signed out and will go to our homepage.')) ?></p>
<script>
require([
    "jquery",
    "mage/mage"
], function($){

    $($.mage.redirect("<?= $block->escapeJs($block->escapeUrl($block->getUrl())) ?>", "assign", 1));

});
</script>
