<?php
    $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
    $storeManager = $objectManager->get('Magento\Store\Model\StoreManagerInterface');
    $store = $storeManager->getStore();
    $mediaUrl = $store->getBaseUrl(\Magento\Framework\UrlInterface::URL_TYPE_MEDIA);
?>
<form action="http://www.xend.com.ph/Tracker.aspx" target="_blank">
    <div class="xtwcontainerdiv" style="width: 140px; height: 155px; margin: 0px auto; background-image: url('<?php echo $mediaUrl?>customer/trackerwidget.png');">
        <div class="xtwwaybilldiv" style="padding-top: 60px;">
            <span class="xtwwaybillspan" style="padding-left: 5px;">
                <input style="width: 123px; font-size: 110%; color: dimgray;font-weight:normal" type="text" name="waybill">
            </span>
        </div>
        <div class="xtwsubmitdiv" style="padding: 8px 0 0 34px;">
            <input class="xtwsubmitinput" style="width: 73px; height: 25px; background: transparent; cursor: pointer; border: none;" type="submit" value="">
        </div>
</div>
</form>