<style type="text/css">
	.form-error.invalid-feedback {
        position: relative!important;
	}
	.notice-error {
		background-color: red;
		
	}
	.err_msg {
		color: red;
		border: solid 1px red;
		padding: 5px;
		margin-bottom: 10px;
	}
	.modal-bulk-order .modal-header {
		padding: 10px 10px 10px 10px !important;
		background-color: #353433;
		color: #ffff;
		border-top-right-radius: 0 !important;
		border-top-left-radius: 0 !important;
	}

	.modal-bulk-order .modal-title {
		background:unset !important;
		border-bottom: none !important;
		padding: 0 !important;
		font-size: 16px !important;
	}

	.form-group>label.required::after {
		content: " *";
		color: red;
	}

	.modal-bulk-order .modal-content {
		width:100%;
		padding-top: 3rem !important;
		padding: 10px 10px 10px 10px !important;
		border-radius: 0 !important;
	}
	
	.modal-bulk-order  .modal-inner-wrap {
		width: 50% !important;
	}

	.login_form,
	.emp-forgotpassword, .login_resendlink, .addemp_info, .ok_empinfo
	{
		display: none;
	}
	.form-error {
        display: none;
	}
	#upload_csv {
		width: 35%;
		border: 1px solid #b7b3b3;
		padding: 3px;
	}
	#csv-upload, .btn-cancel {
		padding: 2px 20px;
	}
	.btn-ok, .btn-cancel{
		cursor: pointer;
		border: solid #ccc 1px;
		text-align: center;
		border-radius: 5px;
	}
	.btn-ok:hover, .btn-cancel:hover{
		background-color: #049DEC;
    	color: #fff;
	}
</style>
<div id="myModal" class="popup-content" style="display:none;">
	<div class="justify-content-center">
		<div id="successMsg" class="form-group"></div>
		<div id="continueshopping" class="form-group" style="text-align:center"></div>
		<form id="bulkOrder" method="post" class="emp_idform col-md-12" enctype="multipart/form-data">
            <div class="form-group">
				<label for="exampleInputEmail1" class="required">Upload file</label>
				<input type="file" name="upload_csv" id="upload_csv" style="width:100%;">
				<div class="form-error invalid-feedback">
					<span class="notice-error">Please</span>
				</div>
			</div>
			<div class="form-group">
				<div class="save_empinfo">
					<div class="form-group">
						<label id="csv-upload" class="btn-ok">Upload</label>
						<label class="btn-cancel">Cancel</label>
					</div>
				</div>
			</div>
        </form>
    </div>
</div>