<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var $block \Magento\Framework\View\Element\Html\Links */
$current_url = explode('/',$block->getRequest()->getUriString());
$url_segment = strtolower(@$current_url[3].'/'.@$current_url[4].'/'.@$current_url[5]);
$li_class_edit = strpos($url_segment, "customer/account/edit")  !== false ? 'current' : '';
$li_class_history = strpos($url_segment, "sales/order/")  !== false ? 'current': '';
$li_class_default =  $url_segment == "customer/account/" ? 'current' : '';
//$li_class_default =  strpos($url_segment, "customer/account/") !== false ? 'current' : '';
// if($url_segment == 'customer/account/edit'){
//     $li_class_edit = 'current';
// }elseif($url_segment == 'sales/order/history/'){
//     $li_class_history = 'current';
// }else{
//     $li_class_default = 'current';
// }
?>

<div class="block block-account">
    <div class="title">
        <strong><?= $block->escapeHtml(__('My Account')) ?></strong>
    </div>
    <div class="block-content">        
        <ul>            
            <li data-url="<?=$url_segment?>" class="<?php echo $li_class_default?>">
                <a href="<?php echo $this->getUrl("customer/account/")?>">Account Dashboard</a>
            </li>                
            <li class="<?php echo $li_class_edit?>"><a href="<?php echo $this->getUrl("customer/account/edit")?>">Account Information</a></li>
            <li class="<?php echo $li_class_history?>"><a href="<?php echo $this->getUrl("sales/order/history")?>">My Orders</a></li>
        </ul>
    </div>
</div>
<style>

.mydashboardside .block-content {
    background: none repeat scroll 0 0 #F2F2F2;
    padding: 10px 10px 10px 10px;
    border-left:1px solid #DDDDDD !important;
    border-right:1px solid #DDDDDD !important;
    border-bottom:1px solid #DDDDDD !important;
    line-height:1.3;
}
.mydashboardside .title {
    background: #403150 !important;
    border-bottom: 1px solid #DDDDDD;
    padding: 2px 10px;
    vertical-align: middle;
    padding: 5px;
    color:white;
    margin:0;
}

.mydashboardside .block-content li a {
    color: #000000;
}

.mydashboardside .block-content li.current {
    font-weight: bold;
}

/* .mydashboardside .block-content li strong{
    font-size:12px;
}
.mydashboardside .block-content li a {
    display: block;
    color: #5f5d5c;
    text-decoration: none !important;
    font-size:12px;
} */
.block-title.you-may-also-like {
    background: #4b599f !important;
    text-align: center;
    color:white;
    margin-bottom: -40px !important;
    padding:6px;
}
.block-content.current{
    font-weight:bold !important;
}
.container_wrapper{
    margin-top: -20px;
    margin-bottom: 10%;
}
.container_wrapper .featured_items{
    padding-bottom: 15%;
    padding-top: 5px;
}
.featured-img{
    width: 44%;
    vertical-align: top;
    padding-right: 5px;
    display: inline-block;
}

.featured-details {
    width: 52%;
    display: inline-block;
}
.item_name{
    font-size: 12px;
}
.item_price {
    padding-top: 12px;
    font-size: 12px;
}
.featured_items button {
    /* background: #fb591b !important; */
    border-radius: 0px;
    width: 50%;
    left: 25%;
    position: relative;
    margin-top:10px;
}
</style>