
<?php $_product = $this->getProduct(); ?>
<?php $_wishlistSubmitUrl = $this->helper('Magento\Wishlist\Helper\Data')->getAddUrl($_product); ?>

<ul class="add-to-links">
<?php if ($this->helper('Magento\Wishlist\Helper\Data')->isAllow()) : ?>
    <li><a href="<?php echo $_wishlistSubmitUrl ?>" onclick="productAddToCartForm.submit(this, this.href); return false;" class="link-wishlist"><?php echo $this->__('Add to Wishlist') ?></a></li>
<?php endif; ?>
<?php
    $_compareUrl = $this->helper('Magento\Catalog\Helper\Product\Compare')>getAddUrl($_product);
?>
<?php if($_compareUrl) : ?>
    <?php /*<li><span class="separator">|</span> <a href="<?php echo $_compareUrl ?>" class="link-compare"><?php echo $this->__('Add to Compare') ?></a></li>*/ ?>
<?php endif; ?>
</ul>
